name: CI

on: [push, pull_request]

jobs:
  run-tests:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup deno
        uses: denolib/setup-deno@v2
      - name: Check code format
        run: deno fmt --check
  run-tests:
    name: Check code lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup deno
        uses: denolib/setup-deno@v2
      - name: Check code linting
        run: deno lint --unstable
